# Generated by Django 5.2.12 on 2026-03-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_productcatalog_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcatalog',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price per kg (DA)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price per kg (DA)', max_digits=10, null=True),
        ),
    ]
